### ISSUE TITLE
fails to build with text-2.1.2

### ISSUE THREAD

**Issue by juhp** [nkarag/haskell-DBFunctor#8]
For Stackage Nightly with ghc-9.10.2:

```
       Building library for DBFunctor-0.1.2.1...                                                               12:58:25 [786/954403]
       [1 of 5] Compiling Paths_DBFunctor                                                                                           
       [2 of 5] Compiling RTable.Core                                                                                               
       /home/curators/work/unpack-dir/unpacked/DBFunctor-0.1.2.1-d0c356399353521e70347b2b5ceb99ca737867e08925067e561cbc168c90a145/sr
c/RTable/Core.hs:1595:86: error: [GHC-87543]                                                                                        
           Ambiguous occurrence ‘show’.                                                                                             
           It could refer to                                                                                                        
              either ‘Prelude.show’,                                                                                                
                     imported from ‘Prelude’ at src/RTable/Core.hs:277:8-18                                                         
                     (and originally defined in ‘ghc-internal-9.1002.0:GHC.Internal.Show’),
                  or ‘T.show’,                                                                                                      
                     imported from ‘Data.Text’ at src/RTable/Core.hs:608:1-21.
            |                                                     
       1595 |                                                     expand i = if i < 10 then "0"++ (show i) else show i
            |                                                                                      ^^^^
                                                                                                                                    
       /home/curators/work/unpack-dir/unpacked/DBFunctor-0.1.2.1-d0c356399353521e70347b2b5ceb99ca737867e08925067e561cbc168c90a145/sr
c/RTable/Core.hs:1595:99: error: [GHC-87543]
           Ambiguous occurrence ‘show’.
           It could refer to     
              either ‘Prelude.show’,                                                                                                
                     imported from ‘Prelude’ at src/RTable/Core.hs:277:8-18
                     (and originally defined in ‘ghc-internal-9.1002.0:GHC.Internal.Show’),
                  or ‘T.show’,
                     imported from ‘Data.Text’ at src/RTable/Core.hs:608:1-21.
            |
       1595 |                                                     expand i = if i < 10 then "0"++ (show i) else show i
            |                                                                                                   ^^^^
        
       /home/curators/work/unpack-dir/unpacked/DBFunctor-0.1.2.1-d0c356399353521e70347b2b5ceb99ca737867e08925067e561cbc168c90a145/sr
c/RTable/Core.hs:1599:86: error: [GHC-87543]
           Ambiguous occurrence ‘show’.
           It could refer to
              either ‘Prelude.show’,
                     imported from ‘Prelude’ at src/RTable/Core.hs:277:8-18
                     (and originally defined in ‘ghc-internal-9.1002.0:GHC.Internal.Show’),
                  or ‘T.show’,
                     imported from ‘Data.Text’ at src/RTable/Core.hs:608:1-21.
            |
       1599 |                                                     expand i = if i < 10 then "0"++ (show i) else show i
            |                                                                                      ^^^^
:
```
